spring.application.name=server-replica1
server.port=8082
node.id=replica1
node.role=REPLICA
node.peers=http://localhost:8081,http://localhost:8083
storage.file=data/database-replica1.txt
request.timeout.ms=1500
