spring.application.name=server-replica2
server.port=8083
node.id=replica2
node.role=REPLICA
node.peers=http://localhost:8081,http://localhost:8082
storage.file=data/database-replica2.txt
request.timeout.ms=1500
